E 2588 etat dhover
onlydustxyz/saas-frontend pull request #804
Opened 2024-12-17 15:09 UTC by alexbeno

2024-12-17 16:09 UTC, haydencleary requested changes

2024-12-17 16:24 UTC, alexbeno commented on design-system/molecules/cards/card-project-marketplace/adapters/default/default.adapter.tsx
> +import { motion, useMotionValue, useTransform } from "framer-motion";
with M style property will not be animated only the available values

2024-12-17 16:24 UTC, alexbeno commented on design-system/molecules/cards/card-project-marketplace/adapters/default/default.adapter.tsx
> +function HoverEffect({ cardRef }: { cardRef: React.RefObject<HTMLDivElement> }) {
A DS component or just a _comoponents folder inside the adapter ?

2024-12-17 16:34 UTC, alexbeno commented on design-system/molecules/cards/card-project-marketplace/adapters/default/default.adapter.tsx
> +function HoverEffect({ cardRef }: { cardRef: React.RefObject<HTMLDivElement> }) {
ok go

2024-12-18 09:12 UTC, haydencleary approved these changes

2024-12-18 09:15 UTC, merged